	var eventInfo = []
	var eventNumb = 33 
	eventInfo[0] = {link: "http://events.br.leagueoflegends.com/events/208387", type: "Torneio online", day: 22, hour: 12, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "EriCat"}
	eventInfo[1] = {link: "http://events.br.leagueoflegends.com/events/208150", type: "Torneio online", day: 22, hour: 13, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Deloytt"}
	eventInfo[2] = {link: "http://events.br.leagueoflegends.com/events/208377", type: "Torneio online", day: 22, hour: 13, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "tramenker"}
	eventInfo[3] = {link: "http://events.br.leagueoflegends.com/events/208466", type: "Torneio online", day: 22, hour: 13, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "paIN smbo Razer"}
	eventInfo[4] = {link: "http://events.br.leagueoflegends.com/events/207757", type: "Torneio online", day: 22, hour: 16, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "TheMored"}
	eventInfo[5] = {link: "http://events.br.leagueoflegends.com/events/199283", type: "Torneio online", day: 22, hour: 18, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Zontar"}
	eventInfo[6] = {link: "http://events.br.leagueoflegends.com/events/184637", type: "Torneio presencial", day: 23, hour: 08, min: 30, map: "Summoner's Rift", pick: "null", creator: "ZeTTaWaTTs"}
	eventInfo[7] = {link: "http://events.br.leagueoflegends.com/events/207835", type: "Torneio online", day: 23, hour: 13, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "mike12408"}
	eventInfo[8] = {link: "http://events.br.leagueoflegends.com/events/203458", type: "Torneio online", day: 23, hour: 13, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Vayne is my Lady"}
	eventInfo[9] = {link: "http://events.br.leagueoflegends.com/events/202054", type: "Torneio presencial", day: 23, hour: 13, min: 00, map: "Summoner's Rift", pick: "null", creator: "EmicidaHang"}
	eventInfo[10] = {link: "http://events.br.leagueoflegends.com/events/208763", type: "Torneio online", day: 23, hour: 13, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Deloytt"}
	eventInfo[11] = {link: "http://events.br.leagueoflegends.com/events/208756", type: "Torneio online", day: 23, hour: 13, min: 00, map: "Summoner's Rift", pick: "null", creator: "SG Naner"}
	eventInfo[12] = {link: "http://events.br.leagueoflegends.com/events/207985", type: "Torneio Misto", day: 24, hour: 00, min: 00, map: "Summoner's Rift", pick: "null", creator: "Drguinhas"}
	eventInfo[13] = {link: "http://events.br.leagueoflegends.com/events/206731", type: "Torneio online", day: 24, hour: 12, min: 00, map: "Summoner's Rift", pick: "null", creator: "PondinFake"}
	eventInfo[14] = {link: "http://events.br.leagueoflegends.com/events/203821", type: "Torneio online", day: 24, hour: 13, min: 00, map: "Summoner's Rift", pick: "null", creator: "EriCat"}
	eventInfo[15] = {link: "http://events.br.leagueoflegends.com/events/206075", type: "Torneio online", day: 24, hour: 14, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Candice Berenice"}
	eventInfo[16] = {link: "http://events.br.leagueoflegends.com/events/206762", type: "Torneio online", day: 24, hour: 14, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Zontar"}
	eventInfo[17] = {link: "http://events.br.leagueoflegends.com/events/202263", type: "Torneio online", day: 24, hour: 15, min: 00, map: "Summoner's Rift", pick: "null", creator: "Wayze Campeonato"}
	eventInfo[18] = {link: "http://events.br.leagueoflegends.com/events/203995", type: "Torneio online", day: 25, hour: 23, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Boccato"}
	eventInfo[19] = {link: "http://events.br.leagueoflegends.com/events/203627", type: "Torneio online", day: 26, hour: 19, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "HXP Vicio"}
	eventInfo[20] = {link: "http://events.br.leagueoflegends.com/events/203997", type: "Torneio online", day: 26, hour: 23, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Boccato"}
	eventInfo[21] = {link: "http://events.br.leagueoflegends.com/events/203193", type: "Torneio online", day: 27, hour: 13, min: 00, map: "Twisted Treeline", pick: " Tournament Draft ", creator: "LBR Max Pita"}
	eventInfo[22] = {link: "http://events.br.leagueoflegends.com/events/206502", type: "Torneio presencial", day: 28, hour: 08, min: 30, map: "Summoner's Rift", pick: "null", creator: "Jaimeknx"}
	eventInfo[23] = {link: "http://events.br.leagueoflegends.com/events/203824", type: "Torneio online", day: 28, hour: 13, min: 00, map: "Summoner's Rift", pick: "null", creator: "EriCat"}
	eventInfo[24] = {link: "http://events.br.leagueoflegends.com/events/207904", type: "Torneio online", day: 22, hour: 19, min: 45, map: "Summoner's Rift", pick: "null", creator: "Blessed 1991"}
	eventInfo[25] = {link: "http://events.br.leagueoflegends.com/events/205019", type: "Torneio online", day: 22, hour: 20, min: 00, map: "Summoner's Rift", pick: "null", creator: "DemonLord6"}
	eventInfo[26] = {link: "http://events.br.leagueoflegends.com/events/203991", type: "Torneio online", day: 22, hour: 23, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Boccato"}
	eventInfo[27] = {link: "http://events.br.leagueoflegends.com/events/200077", type: "Torneio online", day: 23, hour: 13, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "The Lol Tourney"}
	eventInfo[28] = {link: "http://events.br.leagueoflegends.com/events/201998", type: "Torneio online", day: 23, hour: 14, min: 00, map: "Summoner's Rift", pick: "null", creator: "PlayGamer02S"}
	eventInfo[29] = {link: "http://events.br.leagueoflegends.com/events/208161", type: "Torneio online", day: 23, hour: 14, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "Leceido"}
	eventInfo[30] = {link: "http://events.br.leagueoflegends.com/events/207030", type: "Torneio online", day: 23, hour: 14, min: 00, map: "Summoner's Rift", pick: "null", creator: "HEATO"}
	eventInfo[31] = {link: "http://events.br.leagueoflegends.com/events/199728", type: "Torneio online", day: 23, hour: 15, min: 00, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "L3i Kan"}
	eventInfo[32] = {link: "http://events.br.leagueoflegends.com/events/202282", type: "Torneio online", day: 23, hour: 18, min: 30, map: "Summoner's Rift", pick: " Tournament Draft ", creator: "EderMessi"}
	var lastUpdate = '2016-07-22'